public enum TextNames {
    MENU, FULL_NAME, PHONE_NUMBER, CONTACT, NAME, PHONE,
    SUCCESS_ADDED, NOT_SUCCESS_ADD, SHOW,
    SHOW_MODE, NO_CONTACT, ENTER_ORDINAL,
    RENAME_OR_EDIT, ENTER_NAME_OR_PHONE,
    NOT_FOUND, SUCCESS_RENAMED, SUCCESS_EDITED, CONFIRM_DELETE, SUCCESS_DELETE,
    ENTER_NAME_OR_PHONE_DEL, ENTER_NAME_OR_PHONE_SE, SUCCESS_EXIT
}
